* Leadership Philosophy

** Guiding Principles

- (Me): Hire great people, and get out of their way.
- (You): Get your work done, and don’t be an jerk.

** In summary, my job is to:
- provide support for the members of my team to learn, grow and develop; and to help them set, and attain, goals that are meaningful to them
- set a clear vision for my team, and support them in determining the path to fulfilling that vision
- frame the business problems and constraints, so that my team has a clear understanding of what success looks like
- educate the rest of the organization about the capabilities my team provides, and to encourage ongoing communication and collaboration
- hire great people, and create an environment where they can thrive


** I expect the people I support to:
- communicate openly with me; tell me what is working, and what is not
  - /Consider calibrating questions to help determine when things are not going well/
  - /Knowing that my style is more hands off; ask about whether they are getting enough of my time, and support/
- take care of yourself and your teammates (no job should be worth sacrificing time with family and friends)


** The people I support can expect me to:
- shield them from organizational politics as much, or as little, as they want
- try to meet you where you are
- respect your free time as much as I do my own


** What am I doing to grow?
- I hired a coach to help me be a better leader/person.
  - Listen more, talk less.
- I am trying to focus on asking more personal questions.  I want to get to know everyone I work with as an individual.




** Calibrating question ideas

- Do you know what is expected of you at work?
- Do you have the materials and equipment you need to do your work right?
- At work, do you have the opportunity to do what you do best every day?
- Have I given you recognition or praise for doing good work recently?
- Do you feel that I care about you as a person?
- Can I be doing more to encourage your development?
- At work, do you feel that your opinions count?
- Does the mission, or purpose, of the company make you feel your job is important?
- Are your team members (and reports, if applicable) committed to doing quality work?
- Do you have a best friend at work?
- In the last six months, has someone at work (should be me, or their manager for a skip level) talked to you about your progress?
- Have you had opportunities at work to learn and grow in the last year?

